name: CI cache

on: workflow_dispatch

jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          # Useful for caching dependencies in monorepos:
          cache-dependency-path: yarn.lock

      - name: Install dependencies with retry
        run: |
          for i in {1..3}; do
            yarn install --frozen-lockfile && break
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done

      ### - run: yarn test
